---
- name: iniciar primeiro no
  command: kubeadm init
  register: kubeadm_init_output
  when: inventory_hostname == 'master0'
  ignore_errors: yes

- name: criar diretorio .kube no root
  file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: copiar o arquivo de configuracao do kubectl
  command: "cp /etc/kubernetes/admin.conf /root/.kube/config"
  when: kubeadm_init_output.rc == 0

- name: criar o usuario kube
  user:
    name: kube
    group: wheel
    state: present

- name: senha para o kube
  user:
    name: kube
    password: "{{ kube_password | password_hash('sha512') }}"
  when: kubeadm_init_output.rc == 0

    #- name: Definir o contexto kubectl para usar o arquivo de configuracao
    #command: "kubectl config set-context --current --namespace=kube-system"
    #when: kubeadm_init_output.rc == 0

- name: instalar rede CNI
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/calico.yaml 
  when: kubeadm_init_output.rc == 0

- name: label dos worker
  command: kubectl label node worker0 node-role.kubernetes.io/worker=worker
  when: kubeadm_init_output.rc == 0

- name: label dos worker
  command: kubectl label node worker1 node-role.kubernetes.io/worker=worker
  when: kubeadm_init_output.rc == 0

- name: ativar metricas dos pods
  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.6.3/components.yaml
  when: kubeadm_init_output.rc == 0

- name: comando para adicionar os worker
  debug:
     msg: "{{ kubeadm_init_output.stdout | regex_search('kubeadm join.*', '\\0') }}"
  when: kubeadm_init_output.rc == 0

  #- name: Adicionar no master 1 ao cluster
  #command: "{{ kubeadm_init_output.stdout | regex_search('kubeadm join.*', '\\0') }} --control-plane"
  #when: inventory_hostname == 'master1' and kubeadm_init_output.rc == 0
  #  register: join_master_output
  #  failed_when: join_master_output.rc != 0
