---
- name: Remover pacote podman
  dnf:
    name: "{{ pacote_remover }}"
    state: absent

- name: Remover pacote podman-docker
  dnf:
    name: "{{ pacote_remover_podman_docker }}"
    state: absent


- name: Remover pacotes relacionados ao runc
  dnf:
    name: "{{ pacote_remover_runc }}"
    state: absent

- name: Limpar o cache do dnf
  command: dnf clean all
      
- name: Desativar swap
  command: swapoff -a
  ignore_errors: true

- name: Desativar no fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*'
    state: absent

- name: Adicionar o repositorio Docker
  command: "{{ repo_docker }}"
  ignore_errors: yes

- name: Instalar Docker
  dnf:
    name: "{{ docker_pacotes }}"
    state: present
    allowerasing: yes

- name: Iniciar o servico do docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Criar repositório Kubernetes
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl={{ k8s_repo_url }}
      enabled=1
      gpgcheck=1
      gpgkey={{ k8s_gpg_key }}
    owner: root
    group: root
    mode: '0644'

- name: Instalar kubelet, kubeadm, kubectl
  dnf:
    name: "{{ k8s_pacotes }}"
    state: present

- name: Instalar o pacote iproute-tc
  dnf:
    name: "{{ iproute_pacote }}"
    state: present
    update_cache: yes


- name: Iniciar o servico do kubelet 
  systemd:
    name: kubelet
    enabled: yes
    state: started
