---
- name: Atualizar hostname
  hostname:
    name: "{{ hostname }}"

- name: Atualizar /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname }}"

- name: Configurar SELinux para desabilitado
  selinux:
    state: disabled

- name: Reboot da maquina
  reboot:
    reboot_timeout: 300
    test_command: whoami
