---
- name: atualizar hostname 
  hosts: all
  become: yes
  tasks:
    - name: novo hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: atualizar /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^127.0.1.1"
        line: "127.0.1.1 {{ inventory_hostname }}"

